# Site settings
author: Ariel Ibarra
title: Coconut Creations
header-img: img/home-bg.png
email: arielibarra39@gmail.com
copyright_name: Ariel Ibarra
description: > # this means to ignore newlines until "baseurl:"
  A student coding blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Ariel-I

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
